version: "3.7"
services:
        web1:
         image: hanabizhani/hblaratex
        build:
         context: .
         dockerfile: ./Dockerfile
       ports:
        - "8000:80"
       volumes:
        - ./src:/var/www
